project.name: mentoring

discodeit:
  repository:
    type: file
    file:
      user: user.dat
      channel: channel.dat
      message: message.dat


scheduler:
  enabled: true
  cron: 0/10 * * * * ?
